// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vajyvlzsisnhinhirvkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhanl2bHpzaXNuaGluaGlydmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDA3MDIsImV4cCI6MjA2NDA3NjcwMn0.AR0tC095sisUdqOJLgY1zKLlTieBiga0oeKeHm9zGo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);